### PR TITLE
Fixes path.join use

### PR DESCRIPTION
**Pull request by typeoneerror**

### CODE REVIEW

**Review by cibernox — APPROVED** [review]

**Comment by cibernox** [comment]
I don't think the node4 failures is due to this. I'll merge it.

**Comment by roubouen** [comment]
Is this fix on npm?

I was having the same issue. :(

Thanks to both of you.

**Comment by jayvdb** [comment]
No new release at https://github.com/cibernox/ember-k-codemod/releases or https://www.npmjs.com/package/ember-k-codemod :/

**Comment by cibernox** [comment]
Maybe not, I'll publish it

**Comment by cibernox** [comment]
Published in 0.1.7

**Pull request merged**
